#DESAFIO 01
#CRIE UM SCRIPT PYTHON QUE LEIA O NOME DE UMA PESSOA E MOSTRE UMA MENSAGEM DE BOAS - VINDAS DE ACORDO COM O VALOR DIGITADO.

nome=input('qual seu nome ')
print('seja bem vindo a python',nome)
