#DESAFIO 02
#CRIE UM SCRIPT PYTHON QUE LEIA O DIA, O MÊS E O ANO DE NASCIMENTO DE UMA PESSOA E MOSTRE UMA MENSAGEM COM A DATA FORMATADA.

DIA=input('QUAL DIA VOCÊ NASCEU? ' )
MES=input( 'QUAL MÊS VOCÊ NASCEU? ')
ANO=input('QUAL ANO QUE VOCÊ NASCEU? ')
print(DIA,MES,ANO)
